version: '3.9'

services:
  chatgpt:
    image: dockerproxy.com/eryajf/chatgpt-dingtalk:latest
    container_name: chatgpt
    environment:
      - APIKEY=xxxxxx  # 你的 api_key
      - MODEL="gpt-3.5-turbo-0301" # 指定模型
      - SESSION_TIMEOUT=600 # 超时时间
      - HTTP_PROXY=http://host.docker.internal:15777 # 配置代理，注意：host.docker.internal会解析到容器所在的宿主机IP，如果你的服务部署在宿主机，只需要更改端口即可
      - DEFAULT_MODE="单聊" # 聊天模式
    ports:
      - "8090:8090"
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway